language: php

php:
   - "7.2"
   - hhvm
   - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

sudo: false

git:
    submodules: false

before_script:
    - make install

script:
    - make test

notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/cef8275f5f84c3764d22
        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
